name: tribe_quest
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.2
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  #rxdart: ^0.27.1
  get_it: ^7.1.3
  uuid: ^3.0.4
  formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
